### ISSUE TITLE
Team, Governance and Technology

### ISSUE THREAD

**Issue by Bitnation-Pangea** [Bit-Nation/bit-nation.github.io-old#11]
From what I've read about investment decisions and from an analysis of other successful ICO landing pages, I would suggest that users need to easily be able to find information on 1). our team, 2.) our internal Genesis Holon governance mechanism, and 3.) our technology.  Would be useful to links to a summary of these issues on pages - maybe a 1 page pdf, with very high production standard.

**Comment by xsttx** [comment]
+1 for a one pager pdf describing it. I don't want to add to many sections, because I think it's better when it's short and simple (there are already two more sections to be added later on that are more relevant - the download and install Pangea section, and the stats section - see other issues in here.)

**Comment by xsttx** [comment]
Technology section has been added. Governance is in other places like the whitepaper etc. Team will be added later on.
