### ISSUE TITLE
add linkedin/ twitter/ github icons under core contributors photos to link to their personal linkedin/ git/ twitter

### ISSUE THREAD

**Issue by xsttx** [Bit-Nation/bit-nation.github.io-old#76]

**Comment by apravink** [comment]
I can take this on :). Is there a file where these urls exist or should I use google?

**Comment by xsttx** [comment]
Thanks @apravink ! No we don't have a page with it. But I can help you find it if you want?

**Comment by apravink** [comment]
Okay I'll google it and let you know if I cant find something

**Comment by xsttx** [comment]
Great, thanks!

**Comment by apravink** [comment]
Just a quick comment:
There seems to be a problem loading all the external links in  `index.html`  caused by a missing period `.`
So for example, in the current state you have `<link rel="stylesheet" href="/css/main.css">` which does not load `main.css` because it cant find the file. However, when I add the `.` and put in as `<link rel="stylesheet" href="./css/main.css">` it loads fine.

I am using a windows machine so not sure if the error is caused by that?.  I can test on a linux machine when I get home in the evening.

**Comment by apravink** [comment]
Is there a generic github, linkedin and twitter page I can redirect to if the contributors dont seem to have   accounts on those social platforms?. Right now I am redirecting it to the bitnation home page

**Comment by xsttx** [comment]
@apravink how about re-directing it to this page? https://github.com/Bit-Nation/Pangea-Docs/blob/master/README.md

**Comment by xsttx** [comment]
Or I guess the home page (the tse.bitnation.co one) is fine to - maybe that's a better option.
